# This script was autogenerated from cx_freeze using cxfreeze-quickstart
# The resulting script was modified with small changes

from cx_Freeze import setup, Executable


include_files = ['app',
                 'config.py',
                 'app.db']

includes = ['jinja2',
           'jinja2.ext',
            'config',
            'sqlalchemy.sql.default_comparator',
           ]

excludes = ['PyQt5'
            ]

buildOptions = dict(packages = [],
                    includes = includes,
                    include_files = include_files,
                    excludes = excludes,
                    include_msvcr = True
                    )

import sys
base = 'Win32GUI' if sys.platform=='win32' else None

executables = [
    Executable(script='runwindow.py', targetName='VLib.exe', base=base)
]

setup(name='VLib',
      version = '1.0',
      description = 'A library database program',
      options = dict(build_exe = buildOptions),
      executables = executables)
